import type { Metadata } from 'next';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<nav className='p-4 bg-gray-100'>
					<ul className='flex space-x-4'>
						<li>
							<Link href='/' className='text-blue-600 hover:underline'>
								Home
							</Link>
						</li>
						<li>
							<Link href='/about' className='text-blue-600 hover:underline'>
								About
							</Link>
						</li>
						<li>
							<Link href='/contact' className='text-blue-600 hover:underline'>
								Contact
							</Link>
						</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	);
}
